name: Browser Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v6

      - name: Start testserver
        run: bun tests/test-browser-server.js &

      - name: Run Playwright tests
        run: docker run -it --rm --volume ./:/app --ipc=host mcr.microsoft.com/playwright:v1.59.1-noble /bin/bash -c "cd /app/tests && npm i --yes -D @playwright/test@1.59.1 && npx --yes playwright test"