name: Combined PHP and JS Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v6

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: latest
          extensions: openssl

      - name: Setup Node
        uses: https://github.com/actions/setup-node@v6
        with:
          node-version: latest

      - name: Run Tests
        run: node tests/test-js-php.js && php tests/test-js-php.php