name: Browser Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v6

      - name: Setup Bun
        uses: https://github.com/oven-sh/setup-bun@v2
        with:
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"

      - name: Start testserver
        run: bun tests/test-browser-server.js &

      - name: Run Playwright tests
        run: docker run --rm --volume ./:/app --ipc=host mcr.microsoft.com/playwright:v1.59.1-noble /bin/bash -c "cd /app/tests && npm i --yes -D @playwright/test@1.59.1 && npx --yes playwright test"