name: PHP and JS Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  tests:
    strategy:
      matrix:
        phpversion: ["8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]
        nodeversion: ["15.x", "22.x", "24.x", "26.x"]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v6

      - name: Setup PHP ${{ matrix.phpversion }}
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpversion }}
          extensions: openssl

      - name: Setup Node ${{ matrix.nodeversion }}
        uses: https://github.com/actions/setup-node@v6
        with:
          node-version: ${{ matrix.nodeversion }}

      - name: Setup Bun
        uses: https://github.com/oven-sh/setup-bun@v2

      - name: Run PHP isolated Test
        run: php tests/test-encrypt-decrypt.php

      - name: Run NodeJs isolated Test
        run: node tests/test-encrypt-decrypt.js

      - name: Run BUN isolated Test
        run: bun tests/test-encrypt-decrypt.ts

      - name: Run PHP<->JS Tests
        run: node tests/test-js-php.js && php tests/test-js-php.php