name: PHP and JS Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  tests:
    strategy:
      matrix:
        phpversion: ["8.0", "8.1", "8.2", "8.3"]
        nodeversion: ["15.x", "22.x"]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.phpversion }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpversion }}
          extensions: openssl

      - name: Setup Node ${{ matrix.nodeversion }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeversion }}

      - name: Run PHP isolated Test
        run: php tests/test-encrypt-decrypt.php

      - name: Run NodeJs isolated Test
        run: node tests/test-encrypt-decrypt.js

      - name: Run PHP<->JS Tests
        run: node tests/test-js-php.js && php tests/test-js-php.php

#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps

#      - name: Run Playwright tests
#        run: npx playwright test
#
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30