name: PHP Composer Verify
on:
  workflow_dispatch:
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v6

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: latest
          extensions: openssl

      - name: Install dependencies
        run: cd tests && composer require brainfoolong/js-aes-php

      - name: Run Test
        run: php --version && php tests/test-encrypt-decrypt-composer.php